open_graph:
  enable: true
  twitter_id: # for open_graph meta

######## Article ########
article:
  # 文章类型，决定布局风格，可以在 front-matter/topic/wiki 中覆盖此参数
  type: tech # tech: 默认技术类文章, story: 图文类文章，文字和段落间增距大
  # 缩进两个文字宽度，适合文字类博客，可以在 front-matter/topic/wiki 中覆盖此参数
  indent: # true / false
  # 如果没有指定封面，是否根据 tags 作为关键词搜索封面图片？
  auto_cover: false # search from https://source.unsplash.com/
  # 封面图宽高比
  cover_ratio: 2.4
  # 如果没有指定横幅，是否根据 tags 作为关键词搜索横幅图片？
  auto_banner: false # search from https://source.unsplash.com/
  # 如果没有指定 excerpt 和 description，将自动取多长的内容作为文章摘要？
  auto_excerpt: 128
  # 分类颜色
  category_color:
    '探索号': '#f44336'
  # 文章许可协议
  license: '本文采用 [署名-非商业性使用-相同方式共享 4.0 国际](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处。'
  # 分享
  share: # [wechat, weibo, email, link]
  # 相关文章，需要安装插件 (for layout: post)
  # npm i hexo-related-popular-posts

logo:
  subtitle: 'ExquisiteCore | 精致的咸鱼' # '文字1 | 文字2' (鼠标放上去会切换到文字2)

menubar:
  columns: 4 # 一行多少个
  items: # 可按照自己需求增加，符合以下格式即可
    - id: post
      theme: '#1BCDFC'
      title: 博客
      icon: ''
      url: /
      
    - id: about
      theme: ''
      title: 关于
      icon: ''
      url: /about/

    - id: friends
      theme: ''
      title: 友链
      icon: ''
      url: /friends/

    - id: book
      theme: ''
      title: 书籍
      icon: ''
      url: /book/

# 文章搜索
search:
  service: local_search # local_search, todo...
  local_search: # 在 front-matter 中设置 indexing:false 来避免被搜索索引
    field: all # post, page, all
    path: /search.json # 搜索文件存放位置
    content: true # 是否搜索内容
    codeblock: true # 是否搜索代码块（需要content: true)

comments:
  service: giscus
  # giscus
  # https://giscus.app/zh-CN
  giscus:
    src: https://giscus.app/client.js
    data-repo: ExquisiteCore/ExquisiteCore.github.io # [在此输入仓库]
    data-repo-id: R_kgDOK71egQ # [在此输入仓库 ID]
    data-category: General # [在此输入分类名]
    data-category-id: DIC_kwDOK71egc4CdD3i
    data-mapping: pathname
    data-strict: 0
    data-reactions-enabled: 1
    data-emit-metadata: 0
    data-input-position: top # top, bottom
    data-theme: preferred_color_scheme
    data-lang: zh-CN
    data-loading: lazy
    crossorigin: anonymous


######## Main ########
# 站点主结构树
site_tree:
  # -- 列表类页面 -- #
  # 主页配置
  home:
    sidebar: welcome, recent, timeline
  # 博客列表页配置
  index_blog:
    base_dir: blog # 只影响自动生成的页面路径
    menu_id: post # 未在 front-matter 中指定 menu_id 时，layout 为 post 的页面默认使用这里配置的 menu_id
    sidebar: welcome, recent, timeline # for categories/tags/archives
    nav_tabs:  # 近期发布 分类 标签 专栏 归档 and ...
       '生活碎片': /life
  # 博客专栏列表页配置
  index_topic:
    base_dir: topic # 只影响自动生成的页面路径
    menu_id: post # 未在 front-matter 中指定 menu_id 时，layout 为 topic 的页面默认使用这里配置的 menu_id
  # 文档列表页配置
  index_wiki:
    base_dir: wiki # 只影响自动生成的页面路径
    menu_id: wiki # 未在 front-matter 中指定 menu_id 时，layout 为 wiki 的页面默认使用这里配置的 menu_id
    sidebar: toc, ghissues, related, recent # for wiki
    nav_tabs:
      # 'more': https://github.com/xaoxuu
  # -- 内容类页面 -- #
  # 博客文章内页配置
  post:
    menu_id: post # 未在 front-matter 中指定 menu_id 时，layout 为 post 的页面默认使用这里配置的 menu_id
    sidebar: toc, related, ghrepo, ghissues, recent # for pages using 'layout:post'
  # 博客专栏文章内页配置
  topic:
    menu_id: post
  # 文档内页配置
  wiki:
    menu_id: wiki # 未在 front-matter 中指定 menu_id 时，layout 为 wiki 的页面默认使用这里配置的 menu_id
    sidebar: toc, ghissues, related, recent # for wiki
  # 作者信息配置
  author: 
    base_dir: author # 只影响自动生成的页面路径
    menu_id: post
    sidebar: recent, timeline
  # 错误页配置
  error_page:
    menu_id: post
    '404': '/404.html'
    sidebar: recent, timeline
  # 其它自定义页面配置 layout: page
  page:
    sidebar: toc, recent, timeline

footer:
  social:
    Github:
      icon: '<img src="https://github.githubassets.com/assets/github-mark-9be88460eaa6.svg"/>'
      url: https://github.com/ExquisiteCore
    bilibili:
      icon: '<img src="https://ooo.0x0.ooo/2024/02/15/Ov88VI.png"/>'
      url: https://space.bilibili.com/453875890
    Email:
      icon: '<img src="https://ooo.0x0.ooo/2024/02/15/Ov8uqD.png"/>'
      url: mailto:xiaolongqq1y@163.com