version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: blog-postgres
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: Blog
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: blog-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE__URL=postgres://postgres:123456@postgres:5432/Blog
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./blog-web
    container_name: blog-frontend
    environment:
      - HOST=0.0.0.0
      - PORT=4321
    ports:
      - "4321:4321"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
